name: .NET 3.5 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Enable .NET Framework 3.5
      run: |
        dism /online /enable-feature /featurename:NetFX3 /All

    - name: Set up MSBuild path
      uses: microsoft/setup-msbuild@v1.1

    - name: Build with MSBuild
      run: msbuild /p:Configuration=Release
